Processing data model
rbd3/Blog-App pull request #2
Opened 2023-09-21 10:26 UTC by rbd3

### Change made:
👉 Create model classes for all entities
👉 Set up associations between models.

2023-09-21 15:27 UTC, ShadyShawkat requested changes
## Hi @rbd3, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- Correct use of GitFlow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-21 15:27 UTC, ShadyShawkat commented on app/models/user.rb
> +  has_many :comments
- [ ] Kindly ensure that the foreign key is referenced correctly in the comments and likes, much like what you did with the posts: `foreign_key: 'author_id'`.
- [ ] Please create a method for the user model that returns the 3 most recent posts for a given user, as per [this](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project_v1_1.md#:~:text=A%20method%20that%20returns%20the%203%20most%20recent%20posts%20for%20a%20given%20user.) requirement.

2023-09-21 15:27 UTC, ShadyShawkat commented on app/models/like.rb
> +  belongs_to :post
- [ ] Kindly user `author` here instead of `user`.

2023-09-21 15:27 UTC, ShadyShawkat commented on app/models/post.rb
> +  has_many :comments
- [ ] Please create two methods for the post model which are given in the following [requirements](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project_v1_1.md#:~:text=A%20method%20that%20updates,for%20a%20given%20post.).

2023-09-21 15:27 UTC, ShadyShawkat commented on app/models/comment.rb
> +  belongs_to :post
- [ ] Please create a method for the comment model which updates the comments counter for a post,as per [this](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project_v1_1.md#:~:text=A%20method%20that%20updates%20the%20comments%20counter%20for%20a%20post.) requirement.

2023-09-21 15:27 UTC, ShadyShawkat commented on app/models/like.rb
> +  belongs_to :post
- [ ] Please create a method for the like model which updates the comments counter for a post,as per [this](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project_v1_1.md#:~:text=A%20method%20that%20updates%20the%20likes%20counter%20for%20a%20post.) requirement.

2023-09-22 05:39 UTC, binhussen approved these changes
Hi @rbd3 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- Proceeded data models ✔️
- Well Stractured Code ✔️
- Used Git flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-22 05:49 UTC, merged