Views
rbd3/Blog-App pull request #6
Opened 2023-09-28 10:40 UTC by rbd3

### Change made:
👉 Add index for user
👉 Add show for user
👉 Add index for post
👉 Add show for post

2023-09-28 11:40 UTC, julie-ify requested changes
## Hi @rbd3,

Good job so far!

## Highlights!
- Good partial use ✔️ 
- Good model methods use in views ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-28 11:40 UTC, julie-ify commented on app/views/users/_header.html.erb
> +</div>
- [ ] Kindly ensure your page layout matches [the design](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_root_users.png). Styling is not a requirement for this project, but the page layouts should be maintained.

- [ ] Every user should also be a link to their respective user show page.

  ![image](https://github.com/rbd3/Blog-App/assets/81468675/c49fa166-10b3-4f78-b314-6a82065263ce)

2023-09-28 11:40 UTC, julie-ify commented on app/views/users/show.html.erb
> +</a>
- [ ] Kindly ensure the user show page uses [the layout design](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_user_page.png).

  ![image](https://github.com/rbd3/Blog-App/assets/81468675/e5baecec-ad43-42f1-a446-934d3a709868)

2023-09-28 11:40 UTC, julie-ify commented on app/views/posts/index.html.erb
> +      <p><%= comment.user.name %>: <%= comment.text %></p>
- [ ] There is an error when I visit the post index page. Kindly fix it. This should be `author`, not `user`, according to your model.

- [ ] Each post on the index page should also be a link to the post's show page.

- [ ] Also ensure the design follows [the layout](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_user_all_posts.png)

  ![image](https://github.com/rbd3/Blog-App/assets/81468675/82020f46-c60c-412d-b680-a77e2121c666)

2023-09-28 11:40 UTC, julie-ify commented on app/views/posts/show.html.erb
> +      <p><%= comment.user.name %>:
- [ ] I also get errors when I visit the post show page. Kindly fix it. This should be `author`, not `user`, according to your model.

- [ ] Also ensure the page wireframe conforms to [the design](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_single_post.png).

  ![image](https://github.com/rbd3/Blog-App/assets/81468675/6f24872f-0bff-481d-9529-d05564d7d81f)

2023-09-29 09:41 UTC, KayLemba approved these changes
[[# STATUS: APPROVED :green_circle: :clap: 

Hello @rbd3    , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  . 
Congratulations! 🎉  Keep up the Awesome work 🥂  Keep Rocking 🥇 

HIGHLIGHTS:

- [x]  Your repo is professional  😎 
- [x] Descriptive P.R 💯 
- [x] Professional README file 
- [x] App running as intended. 💯 🥇 
- [x] Views Correctly implemented 




 

 










 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]]

2023-09-29 12:28 UTC, merged